name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          lfs: false
          submodules: false

      - name: Set up environment - Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Configure CMake
        shell: bash
        run: |
          cmake -S ${{ github.workspace }}/lab04dz/hello_world -B ${{ github.workspace }}/lab04dz/hello_world/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic"

      - name: Build
        shell: bash
        run: |
          cmake --build ${{ github.workspace }}/lab04dz/hello_world/build --config Release

      - name: Run Tests
        shell: bash
        run: |
          ${{ github.workspace }}/lab04dz/hello_world/build/hello_world
